spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:C:\\git\\gallery\\db\\db_gallery
# ??????
server:
  # ????HTTP??????8080
  port: 8097
  servlet:
    # ???????
    context-path: /
# MyBatis??
mybatis-plus:
  # ???????
  typeAliasesPackage: com.xinshijie.**.domain
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath*:mapper/**/*Mapper.xml