spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:D:\\git\\gallery\\db\\db_gallery.db
# ??????
server:
  # ????HTTP??????8080
  port: 8098
  servlet:
    # ???????
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# MyBatis??
mybatis-plus:
  # ???????
  typeAliasesPackage: com.xinshijie.**.domain
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
reptile:
  url: https://admin.aiavr.com
image:
  path: E:\\folder\\sjk
