spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mail:
    host: smtp.zoho.com    # Replace with your SMTP host
    port: 587                          # Replace with your SMTP port
    username: admin@aiavr.uk
#    password: huanglu33573
    password: v3xMXbzvLTUR
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #  datasource:
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driverClassName: org.sqlite.JDBC
  #    url: jdbc:sqlite:D:\\git\\gallery\\db\\db_gallery.db
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/gallery?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    username: root
#    password: wiki@335610
  #    url: jdbc:mysql://127.0.0.1:3306/gallery?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  #    username: root
  #    password: wiki@335610
    url: jdbc:mysql://103.231.255.132:3306/gallery_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: gallery_test
    password: t8ZtiScXtsXTrGTF
  data:
    redis:
      host: 43.131.248.108
      port: 6379
      database: 0
      password: sha@335610
      timeout: 10s
  rabbitmq:
     host: 47.116.1.65
     port: 5672
     username: wiki
     password: wiki@335610
server:
  port: 8098
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
mybatis-plus:
  typeAliasesPackage: com.xinshijie.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  #configuration:
    ## 开启打印sql配置
     #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
reptile:
  url: https://admin.aiavr.com
image:
  path: ./data/e2
  sourceWeb: https://image.51x.uk/xinshijie
ffmpeg:
  path: /Users/luhuang/Documents/git/SubtitleGenerated/src/main/resources/ffmpeg
paypal:
  client:
    id: AWwAGKZhvPE3xSgDh-gRH9sXwNMKDQSzr65ZwaUHp-U7CTbUk-FTnRRjlF0zTpz5LaeDz5rHgcaaekVm
    secret: ECmBhtDZKC-HCsF_4jeWuZk3uiuaicf0k0IU38O8ivuZJFgvgs_5lfS14DvPdtme5FIXyodxj4jclVWe
  api:
    base:
      url: https://api-m.sandbox.paypal.com