spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: org.sqlite.JDBC
#    url: jdbc:sqlite:D:\\git\\gallery\\db\\db_gallery.db
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gallery?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: wiki@335610
#    url: jdbc:mysql://103.231.255.132:3306/gallery?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    username: gallery
#    password: hsAynhaZT8pBGTjj
  data:
    redis:
      host: 43.131.248.108
      port: 6379
      database: 0
      password: sha@335610
      timeout: 10s
server:
  port: 8098
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
mybatis-plus:
  typeAliasesPackage: com.xinshijie.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  configuration:
#    ## 开启打印sql配置
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
reptile:
  url: https://admin.aiavr.com
image:
  path: ./data/e2
  sourceWeb: https://image.51x.uk/xinshijie
