spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: org.sqlite.JDBC
#    url: jdbc:sqlite:D:\\git\\gallery\\db\\db_gallery.db
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xinshijie?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    #    url: jdbc:mysql://43.131.248.108:3306/xinshijie?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: wiki@335610
# ??????
server:
  # ????HTTP??????8080
  port: 8098
  servlet:
    # ???????
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# MyBatis??
mybatis-plus:
  # ???????
  typeAliasesPackage: com.xinshijie.**.domain
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
reptile:
  url: https://admin.aiavr.com
image:
  path: E:\\folder\\sjk
